project_id = "mrfippvowbudtctahgag"

[functions.create_payment]
verify_jwt = false

[functions.complete-signup]
verify_jwt = false

[functions.admin-manage]
verify_jwt = false
[functions.create_subscription]
enabled = true
verify_jwt = false
import_map = "./functions/create_subscription/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_subscription/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_subscription/*.html" ]

[functions.asaas_webhook]
enabled = true
verify_jwt = true
import_map = "./functions/asaas_webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/asaas_webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/asaas_webhook/*.html" ]
